language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - sh -c "mkdir -p ./build/logs"

script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 src/

after_script:
  - php vendor/bin/coveralls -v