language: php

sudo: false

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - ./install-chardet.sh

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --no-interaction --prefer-source
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - mkdir -p ./build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 src/ tests/PHPChardet/

after_script:
  - php vendor/bin/coveralls -v
